# Generated by Django 4.1.7 on 2023-03-23 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100)),
                ('c_code', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ums_id', models.CharField(max_length=20, unique=True)),
                ('courses', models.ManyToManyField(to='appusers.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(to='appusers.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TutorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('A', 'Available'), ('B', 'Booked'), ('C', 'Canceled')], max_length=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appusers.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appusers.student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appusers.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('timeblock', models.CharField(choices=[('A', '8:00-8:20'), ('B', '8:20-8:40'), ('C', '8:40-9:00'), ('D', '9:00-9:20'), ('E', '9:20-9:40'), ('F', '9:40-10:00')], max_length=1)),
                ('status', models.CharField(choices=[('A', 'Available'), ('B', 'Booked'), ('C', 'Canceled')], max_length=1)),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appusers.student')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appusers.course')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appusers.tutor')),
            ],
        ),
    ]
