# Generated by Django 4.1.7 on 2023-03-29 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appusers.course'),
        ),
    ]
