# Generated by Django 4.1.7 on 2023-04-01 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0005_alter_availability_tutor_alter_student_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='appusers.tutor'),
        ),
    ]
