# Generated by Django 4.2 on 2023-04-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0006_alter_availability_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='semester',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
