# Generated by Django 4.1.7 on 2023-04-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0006_alter_availability_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='semester',
            field=models.CharField(choices=[('F', 'Fall'), ('SU', 'Summer'), ('SP', 'Spring')], max_length=2, null=True),
        ),
    ]
